// Naming: ACTION_ENTITY_RESULT
export default {
    GET_POKEMONS_REQUEST: 'GET_POKEMONS_REQUEST',
    GET_POKEMONS_SUCCESS: 'GET_POKEMONS_SUCCESS',
    GET_POKEMONS_FAILURE: 'GET_POKEMONS_FAILURE',
};
